stages:
  - test

test:
  stage: test
  image: node:14  # Choose an appropriate Node.js version
  script:
    - npm install -g newman
    - newman run Collection\KT.postman_collection.json -e Environment\Lab.postman_environment.json  -r junit,cli
  artifacts:
    paths:
      - newman/*.xml
